INSERT INTO TB_PRODUTO(CODIGO, NOME, VALOR, ESTADO) VALUES (1111, 'PENTE', 100.00, 'NOVO');
INSERT INTO TB_PRODUTO(CODIGO, NOME, VALOR, ESTADO) VALUES (1111, 'RAÇÃO XYZ', 100.00, 'NOVO');

INSERT INTO TB_ESTOQUE (QUANTIDADE, PRODUTO_ID) VALUES (10,1);
INSERT INTO TB_ESTOQUE (QUANTIDADE, PRODUTO_ID) VALUES (5,2);